#server:
#  port: 8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: helloworld
#    key-store-type: PKCS12
#    key-alias: myalias

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/encryption
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.data: INFO
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.springframework.security: DEBUG
    com.mgen.pgen.encryption: DEBUG
  pattern:
    level: "%clr(%5p) %clr([%t])"